### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by gyoo18** [minecraft-linux/mcpelauncher-ui-manifest#33]
Hi, I just logged in to my google account on the laucher when I received a notification about an unknown device that is definitly not one of mine logging in my account. I would like to know if it is related to the launcher and if it is the doing of it, I would like to get some explanations please.

**Comment by ChristopherHX** [comment]
You mean that the launcher identifies itself as a samsung galaxy? Google blocked this launcher, because it was idendified by google as qtwebengine on linux/mac.
Related Change:
https://github.com/minecraft-linux/playdl-signin-ui-qt/compare/20c9f5bf5d8538210b72415935d80f9315f7e85e...9336f1f6ec801b81ab5ea493aa2d693dcfbb7f52#diff-f60d99dd783b889386dcd62f62a46a9d98ef41655b9ed10502a0261d1fec22ee

**Before this change google greets you that this device is insecure, since ca. 2019.8**

Another points of missing security:
- The launcher doesn't encrypt your google access token on your device, it is stored in plain text
- The launcher is not a signed application, you might find a modified version of it which uploads your credentials or do other scary things.
- You may get banned by google, because this launcher is not google play certified (never heard that, but they could do something like that if they want)

**Comment by gyoo18** [comment]
Ok, so if I understand correctly, nobody signed up in my account and it's just that my chromebook didn't identify itself as a chromebook, but as a samsung galaxy. Thanks for reassuring me! :)

**Comment by ChristopherHX** [comment]
Added as a warning in v0.2.3
