### ISSUE TITLE
Error[405] on any version attempted to download

### ISSUE THREAD

**Issue by tacohitbox** [minecraft-linux/mcpelauncher-ui-manifest#41]
**Describe the bug**

**To Reproduce**
1. Build from source and open launcher.
2. Sign into Google Play.
3. Go to any version in the version list .
4. Click "Download and Play".

**Expected behavior**
It to download and play as normal.

**Screenshots**
I screen recorded me signing in, with password hidden, right over [here](https://files.gay/r/jcw7k/2022-06-19%2014-37-35.mp4)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: Latest git commits
 - Installation Type: Built from source

**Additional context**
I have a VPN on when I recorded this but I tried signing in with it on *and* off with no luck.

**Comment by ChristopherHX** [comment]
I have seen such 405 errors starting with 1.14.60.5/1.15beta on armhf ( 2020, 2 years ago ).
What happens if you compile the UI with c++ flag `-DGOOGLEPLAYDOWNLOADER_USEQT`? e.g. `cmake -DCMAKE_CXX_FLAGS=-DGOOGLEPLAYDOWNLOADER_USEQT`. I added it due to temporary issues with the flatpak runtime, but they are solved.

You sign in has no issues, since google play shares the apk download url with you. You can download all apks from the urls printed to the teminal as long you have compiled a debug build. Then import them from settings.

**Comment by tacohitbox** [comment]
This worked for me too! Many thanks!
