### ISSUE TITLE
Weird error message when I try to download Minecraft in the launcher

### ISSUE THREAD

**Issue by threedogsinatrenchcoat** [minecraft-linux/mcpelauncher-ui-manifest#42]
So, whenever I try to download the latest version of Minecraft through the launcher, an error message keeps showing up saying "Failed to open output file".  This pops up with every version of Minecraft I try to download except for version 1.14.60.5. Could anyone help me with this? Thanks.
EDIT: Now every version shows the error message. Could someone please help me with this?

**Comment by ChristopherHX** [comment]
Should be fixed by https://github.com/minecraft-linux/mcpelauncher-ui-manifest/commit/485df2e65790bea348cf9397e4ad49b3002dbe8d ( qt6 branch ). 
This launcher used to save the apk files in /tmp, if your app has permission problems accessing /tmp or it is too small for the game you might see this kind of errors.

**Comment by Blanky-png** [comment]
I'm pretty new to Linux, just got a steam deck, how would I fix this same bug in beginner terms?

**Comment by ChristopherHX** [comment]
Do you have enough disk space where the launcher tries to store the apk's? "Failed to open output file" typically means you ran out of diskspace. (previously out of diskspace tmp folder)

You can open the folder in settings -> Open GameData Folder then there is a folder called `apks`
